repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # renovate: version=v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: ["--autofix", "--indent=2", "--no-sort-keys"]
      - id: trailing-whitespace

  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e # renovate: version=v8.30.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: d1b833175a5d08a925900115526febd8fe71c98e # renovate: version=v0.15.11
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95 # renovate: version=v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: 6d3c1b70d44ea2202b23552af93aca3b5017ee83 # renovate: version=v0.9.36
    hooks:
      - id: pymarkdown
        args: ["--config", "pymarkdown.json", "scan"]
